const productData = {
  data: [
    {
      after: 584,
      before: 1499,
      desc: "Printed Casual Shirt",
      stars: 4,
      reviews: "36.4k",
      brand: "roadster",
      title: "Roadster",
      img: "https://drive.google.com/uc?export=view&id=14suEUABEQPGEg_qs2JgsBJF4iVWjjMBV",
      wished: 1,
      bagged: 0,
    },
    {
      after: 599,
      before: 1499,
      desc: "Cotton Casual Shirt",
      stars: 3,
      reviews: "20.1k",
      brand: "roadster",
      title: "Roadster",
      img: "https://drive.google.com/uc?export=view&id=1yJ6C1athI3YAktf6Q8Rnoa3Ua7nrGKjT",
      wished: 0,
      bagged: 1,
    },
    {
      after: 549,
      before: 899,
      desc: "Checked Casual Shirt",
      stars: 4,
      reviews: "9.1k",
      brand: "roadster",
      title: "Roadster",
      img: "https://drive.google.com/uc?export=view&id=1y_-f4CwnAW0Bac1J3XwfRwkE6Zz3Vdhz",
      wished: 0,
      bagged: 1,
    },
    {
      after: 649,
      before: 1599,
      desc: "Cotton Casual Shirt",
      stars: 3,
      reviews: "5.2k",
      brand: "roadster",
      title: "Roadster",
      img: "https://drive.google.com/uc?export=view&id=1e0wFNM1KmGGFlVslqqqj41_Ke1CFRX3g",
      wished: 0,
      bagged: 0,
    },
    {
      after: 1199,
      before: 2399,
      desc: "Pure Cotton Casual Shirt",
      stars: 4,
      reviews: 210,
      brand: "indian",
      title: "Indian Terrain",
      img: "https://drive.google.com/uc?export=view&id=1rHTAcvur_4HhJK_06kKTRJYegTYjOvaV",
      wished: 1,
      bagged: 0,
    },
    {
      after: 1500,
      before: 2219,
      desc: "Pure Cotton Casual Shirt",
      stars: 3,
      reviews: 210,
      brand: "indian",
      title: "Indian Terrain",
      img: "https://drive.google.com/uc?export=view&id=1nyWZfX_z0RT4quan5iKQdntzL-rQTcBb",
      wished: 0,
      bagged: 0,
    },
    {
      after: 949,
      before: 1599,
      desc: "Collar Cotton Casual Shirt",
      stars: 4,
      reviews: "1k",
      brand: "indian",
      title: "Indian Terrain",
      img: "https://drive.google.com/uc?export=view&id=1ipzX0prhiUrrWaf9VwAT5zhKLILtuOD6",
      wished: 0,
      bagged: 0,
    },
    {
      after: 1049,
      before: 1599,
      desc: "Checked Casual Shirt",
      stars: 3,
      reviews: 65,
      brand: "indian",
      title: "Indian Terrain",
      img: "https://drive.google.com/uc?export=view&id=13U0fEb297Q60H_04DPJl_jDu9n-iRbNy",
      wished: 0,
      bagged: 0,
    },
  ],
};

export default productData;
